name: deploy
on:
  workflow_dispatch:
jobs:
    deploy:
      name: deploy to staging
      runs-on: ubuntu-latest
      steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
            host: ${{ secrets.STAGING_HOST }}
            username: staging
            key: ${{ secrets.STAGING_PRIVATE_KEY }}
            port: 22
            script: "cd /var/www/dodavpn.com; git pull origin main; php artisan optimize:clear"



